# Site settings
title: zhangge的世界
description: 一个IT初学者
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/zhangzheng315/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://github.com/zhangzheng315/zhangzheng315" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
# facebook: facebook
# twitter: twitter
github:  zhangzheng315

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: samanyougarg #github username
repo: zhangzheng315 #github repository
branch: master #branch
relative_source: ../zhangzheng315/ #source directory
destination: ../zhangzheng315-pages/ #destination directory
production_url:  https://samanyougarg.com/
source_url:  https://github.com/zhangzheng315/zhangzheng315 #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
